"""Turn the 7.08 M-row NIS Core file into a compact transaction matrix.

One discharge = one transaction = the set of ICD-10-CM codes recorded in
I10_DX1..I10_DX40.

Design notes:

* The 40 diagnosis column names come from ``config.DX_COLS``, generated by
  a range rather than typed out. A hand-written list of 40 near-identical
  names is one transposition away from silently dropping a column, and
  nothing would raise — a missing entry in a list literal is just a
  shorter list.
* The file is streamed in 500,000-row chunks straight into a sparse CSR
  matrix. The equivalent dense one-hot table would be 7.08 M x 38,927 and
  could not be held in memory; sparse, the whole file fits in ~1 GB, so
  none of it has to be sampled away.

Output (cache/, gitignored) is aggregate-shaped but still derived from
record-level data, so it is treated as restricted.

Run:  python src/build_transactions.py
"""
from __future__ import annotations

import time

import numpy as np
import pandas as pd
import pyreadstat
import scipy.sparse as sp

from config import CACHE, CODE_LOOKUP, CODE_LOOKUP_SHEET, DX_COLS, SAV

CHUNK = 500_000
EXTRA_COLS = ["AGE", "FEMALE", "DISCWT", "I10_NDX", "DIED", "LOS"]


def build() -> None:
    t0 = time.time()

    vocab: dict[str, int] = {}
    indices_parts: list[np.ndarray] = []
    row_lengths_parts: list[np.ndarray] = []
    meta_parts: list[pd.DataFrame] = []

    offset = 0
    while True:
        df, _ = pyreadstat.read_sav(
            str(SAV),
            usecols=DX_COLS + EXTRA_COLS,
            row_offset=offset,
            row_limit=CHUNK,
        )
        n_chunk = len(df)
        if n_chunk == 0:
            break

        arr = df[DX_COLS].to_numpy(dtype=object)
        arr[pd.isna(arr)] = ""

        # NIS pads unused diagnosis slots with "".
        # np.nonzero walks row-major, so `vals` comes out grouped by
        # discharge already — no per-row Python loop needed.
        mask = arr != ""
        rows = np.nonzero(mask)[0].astype(np.int64)
        vals = arr[mask]

        # Deduplicate to the few thousand distinct codes *before* doing any
        # per-string work: stripping 6 M strings costs a U-dtype copy of the
        # whole chunk, stripping the unique set costs nothing.
        uniq_vals, inv = np.unique(vals.astype(str), return_inverse=True)
        remap = np.empty(len(uniq_vals), dtype=np.int64)
        for k, code in enumerate(uniq_vals):
            code = code.strip()
            # A handful of records carry HCUP's invalid/incomplete
            # sentinels; drop them rather than letting them become
            # "diagnoses" with real support.
            if not code or code in ("incn", "invl"):
                remap[k] = -1
                continue
            idx = vocab.get(code)
            if idx is None:
                idx = len(vocab)
                vocab[code] = idx
            remap[k] = idx
        ids = remap[inv]

        good = ids >= 0
        rows, ids = rows[good], ids[good]

        # Dedupe within a discharge: a code listed twice is still one
        # condition, and duplicates would inflate every co-occurrence.
        # Packing (row, id) into one int64 makes that a single np.unique,
        # which also leaves each row's ids sorted — what CSR wants.
        packed = np.unique(rows * np.int64(1 << 32) + ids)
        prow = packed >> 32
        pid = (packed & np.int64(0xFFFFFFFF)).astype(np.int32)
        lengths = np.bincount(prow, minlength=n_chunk).astype(np.int32)

        indices_parts.append(pid)
        row_lengths_parts.append(lengths)
        meta_parts.append(df[EXTRA_COLS].astype(np.float32))

        # Release the chunk's ~1 GB of Python string objects before the next
        # read allocates its own.
        del arr, mask, rows, vals, uniq_vals, inv, ids, packed, prow, df

        offset += n_chunk
        print(f"  {offset:>9,} rows | {len(vocab):>6,} distinct codes | {time.time() - t0:6.1f}s")
        if n_chunk < CHUNK:
            break

    indices = np.concatenate(indices_parts)
    lengths = np.concatenate(row_lengths_parts)
    indptr = np.zeros(len(lengths) + 1, dtype=np.int64)
    np.cumsum(lengths, out=indptr[1:])

    n_rows, n_codes = len(lengths), len(vocab)
    X = sp.csr_matrix(
        (np.ones(len(indices), dtype=np.int8), indices, indptr),
        shape=(n_rows, n_codes),
    )

    code_names = np.empty(n_codes, dtype=object)
    for code, i in vocab.items():
        code_names[i] = code

    meta = pd.concat(meta_parts, ignore_index=True)

    sp.save_npz(CACHE / "transactions.npz", X)
    np.save(CACHE / "code_index.npy", code_names)
    np.savez(CACHE / "row_meta.npz", **{c: meta[c].to_numpy() for c in EXTRA_COLS})

    print(f"\n{n_rows:,} discharges x {n_codes:,} distinct ICD-10-CM codes")
    print(f"{X.nnz:,} coded diagnoses, mean {X.nnz / n_rows:.2f} per discharge")
    print(f"built in {time.time() - t0:.0f}s")

    # The NIS is a 20% stratified sample, so in principle every count should
    # be DISCWT-weighted. Report the weight spread so the choice to analyse
    # unweighted is a documented decision rather than an oversight.
    # float64 for the spread: these values all sit near 5.0, and a float32
    # sum of squares loses so much precision to cancellation that the
    # standard deviation comes out ~1800x too large.
    w = meta["DISCWT"].astype(np.float64)
    print(
        f"\nDISCWT: min {w.min():.4f}  max {w.max():.4f}  "
        f"mean {w.mean():.4f}  CV {w.std() / w.mean():.2e}"
    )
    print(f"weighted national estimate: {w.sum():,.0f} discharges")


def build_code_lookup() -> pd.DataFrame:
    """ICD-10-CM code -> (description, CCSR category, CCSR description).

    Two details in the AHRQ workbook that need care: it opens with four
    non-code rows (Total/Blank/incn/invl), which are selected out by value
    rather than by position, and descriptions are stored as
    ``"A000   : Cholera due to ..."`` — split on the *first* colon only,
    since plenty of descriptions contain another one further along.
    """
    df = pd.read_excel(CODE_LOOKUP, sheet_name=CODE_LOOKUP_SHEET, usecols=[0, 1, 2, 3])
    df.columns = ["code", "description", "ccsr", "ccsr_description"]

    df = df[~df["code"].isin(["Total", "Blank", "incn", "invl"])].copy()
    df["code"] = df["code"].astype(str).str.strip()

    # Descriptions are stored as "A000   : Cholera due to ...".
    desc = df["description"].astype(str)
    split = desc.str.split(":", n=1)
    df["description"] = np.where(
        split.str.len() == 2, split.str[-1].str.strip(), desc.str.strip()
    )

    df["ccsr_description"] = (
        df["ccsr_description"].astype(str).str.replace(r"^\w{3}\d{3}\s+", "", regex=True)
    )
    return df.drop_duplicates("code").set_index("code")


if __name__ == "__main__":
    build()
    lookup = build_code_lookup()
    lookup.to_csv(CACHE / "code_lookup.csv")
    print(f"\ncode lookup: {len(lookup):,} codes, {lookup['ccsr'].nunique():,} CCSR categories")
